global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # INFRASTRUCTURE MONITORING
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8082']  # CHANGED PORT
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  # CUSTOM PIPELINE METRICS
  - job_name: 'pipeline-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
    scrape_interval: 30s
